# -*- coding: utf-8 -*-
"""mnist verisi ile model performans arttırma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVuxie2S9ukoAi-aTjKGxwI8nvt0HJha
"""

import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.datasets import mnist

(X_train , y_train) , (X_test , y_test) = mnist.load_data()

print(X_train.shape , y_train.shape)
print(X_test.shape , y_test.shape)

#model kurma
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(512 , activation="relu"),
    tf.keras.layers.Dense(512 ,  activation="relu"),
    tf.keras.layers.Dense(10 , activation="softmax")

    ])

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"] )

#model eğitimi
model.fit(X_train , y_train , epochs=10)

import numpy as np
#normalleştirme
X_train = (X_train /255.0).astype(np.float32)
X_test  = (X_test /255.0).astype(np.float32)

#tekrar model eğitimi
model.fit(X_train , y_train , epochs=10)

#model değerlendirme
model.evaluate(X_test , y_test)

#standartlaştırma
mean = np.mean(X_train)
std = np.std(X_train)
X_train = ((X_train - mean)/std).astype(np.float32)

#tekrar model eğitimi
model.fit(X_train , y_train , epochs=10)

