# -*- coding: utf-8 -*-
"""model kaydetme & yükleme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dgPQInuRg_yHNwJjSkh81vqoPlsU_H4
"""

import tensorflow as tf
from tensorflow import keras
(train_images , train_labels) , (test_images , test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]
train_images = train_images[:1000].reshape(-1,28*28) /255.0
test_images = test_images[:1000].reshape(-1,28*28) / 255.0

def create_model():
  model = tf.keras.models.Sequential ([
       keras.layers.Dense(512, activation="relu", input_shape=(784,)),
       keras.layers.Dropout(0.2),
       keras.layers.Dense(10)
  ])
  return model

model = create_model()

model.compile(optimizer="adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

model = create_model()
model.summary()

#chechkpoint callback

checkpoint_path = "training_1/my_checkpoints.weights.h5"

import os

chechkpoint_dir = os.path.dirname(checkpoint_path)

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    save_weights_only=True
)

os.listdir(chechkpoint_dir)

model=create_model()

model=create_model()
model.compile(optimizer="adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

loss , acc = model.evaluate(test_images , test_labels )
print(f"Eğitilmemiş modelin doğruluğu {100 * acc : .2f}%")

model.load_weights(checkpoint_path)

loss , acc = model.evaluate(test_images , test_labels )
print(f"Eğitilmiş modelin doğruluğu {100 * acc : .2f}%")

#callback opsiyonları

checkpoint_path = "training_2/cp-{epoch:04d}.weights.h5"

checkpoint_dir = os.path.dirname(checkpoint_path)

batch_size = 32

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    save_weights_only=True,
    save_freq = 5 * batch_size
)

model = create_model()

model = create_model()
model.compile(optimizer="adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

model.fit(train_images , train_labels,
          epochs=50,
          batch_size=batch_size,
          validation_data=(test_images , test_labels),
          callbacks = [checkpoint_cb],
          verbose=0 )

print(f"Contents of checkpoint directory: {os.listdir(checkpoint_dir)}")
os.listdir(checkpoint_dir)

latest = tf.train.latest_checkpoint(checkpoint_dir)
print(f"Latest checkpoint: {latest}")
latest

model=create_model()

latest_path = os.path.join(checkpoint_dir, 'cp-0050.weights.h5')
model.load_weights(latest_path)

model=create_model()
model.compile(optimizer="adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

loss , acc = model.evaluate(test_images , test_labels )
print(f"Restore edilmiş modelin doğruluğu {100 * acc : .2f}%")

#early stopping callback

early_stopping_cb = tf.keras.callbacks.EarlyStopping(
    patience = 5 ,
    restore_best_weights=True

)

checkpoint_path = "training_3/checkpoint.weights.h5"
checkpoint_dir = os.path.dirname(checkpoint_path)

checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    save_weights_only=True,
)

model.fit(train_images , train_labels,
          epochs=50,
          validation_data=(test_images , test_labels),
          callbacks=[checkpoint_cb , early_stopping_cb])

#tüm modeli kaydetme

!mkdir saved_model

model.save("saved_model/my_model.keras")

!ls saved_model/my_model.keras

#model yükleme

new_model = create_model()
new_model = tf.keras.models.load_model("saved_model/my_model.keras")

new_model.summary()

model=create_model()
model.compile(optimizer="adam",
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

loss , acc = model.evaluate(test_images , test_labels )
print(f"Restore edilmiş modelin doğruluğu {100 * acc : .2f}%")

